version: "3.9"
services:
  app:
    build: 
      context: .
    tty: true
    volumes:
      - ./src:/app
      - ./src/node_modules:/app/
    ports:
      - "3000:3000"
    # working_dir: /app
    command: bash -c "npm run dev"
