import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import './globals.css'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'VR App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()
  console.log("layoutsession", session)
  
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
          <Script
            src="https://aframe.io/releases/1.5.0/aframe.min.js"
          />
          {/* Entityにイベントを設定するjs */}
          <Script
            src="https://unpkg.com/aframe-event-set-component@^4.0.0/dist/aframe-event-set-component.min.js"
          />
          <Script
            src="js/play-on-click.js"
            strategy="lazyOnload"
          />
          <Script
            src="js/hide-on-play.js"
            strategy="lazyOnload"
          />
          <Script
            src="js/visible-on-play.js"
            strategy="lazyOnload"
          />
      </html>
    </SessionProvider>
  )
}
