import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'VR App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <Script
          src="https://aframe.io/releases/1.5.0/aframe.min.js"
      />
      <Script
        src="play-on-click.js"
        strategy="lazyOnload"
      />
      <Script
        src="hide-on-play.js"
        strategy="lazyOnload"
      />
    </html>
  )
}
